export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'

export const GET_PLAYERS = 'GET_PLAYERS'
export const GET_PLAYER_ERROR = 'GET_PLAYER_ERROR'
export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const GET_PLAYER = 'GET_PLAYER'
export const CLEAR_PLAYER = 'CLEAR_PLAYER'
export const CLEAR_PLAYERS = 'CLEAR_PLAYERS'